name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24.1.7.0, 21.3.8.21]
    container:
      image: erlang:${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile and run tests
      run: make
    - name: Test with concuerror
      run: make concuerror_test
